In [2]:
import pandas as pd
import numpy as np
from config import api_key
import requests

In [5]:
income_df = pd.read_csv("ACSCP5Y2018.CP03_data_with_overlays_2020-01-29T205006.csv")
income_df

,GEO_ID,NAME,CP03_2014_2018_004E,CP03_2009_2013_004E,CP03_004SS,CP03_2014_2018_005E,CP03_2009_2013_005E,CP03_005SS,CP03_2014_2018_006E,CP03_2009_2013_006E,...,CP03_137SS,CP03_2014_2018_001E,CP03_2009_2013_001E,CP03_001SS,CP03_2014_2018_002E,CP03_2009_2013_002E,CP03_002SS,CP03_2014_2018_003E,CP03_2009_2013_003E,CP03_003SS
0,id,Geographic Area Name,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,Statistical Significance!!EMPLOYMENT STATUS!!P...,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,Statistical Significance!!EMPLOYMENT STATUS!!P...,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,...,Statistical Significance!!PERCENTAGE OF FAMILI...,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,Statistical Significance!!EMPLOYMENT STATUS!!P...,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,Statistical Significance!!EMPLOYMENT STATUS!!P...,2014-2018 Estimate!!EMPLOYMENT STATUS!!Populat...,2009-2013 Estimate!!EMPLOYMENT STATUS!!Populat...,Statistical Significance!!EMPLOYMENT STATUS!!P...
1,0100000US,United States,59.3,57.6,*,3.7,6.2,*,0.4,0.4,...,*,257754872,246191954,*,63.3,64.3,*,62.9,63.8,*

In [9]:
income_df.loc("INCOME")

ValueError: No axis named INCOME for object type <class 'pandas.core.frame.DataFrame'>